apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonweb
  labels:
    app: pythonweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonweb
  template:
    metadata:
      labels:
        app: pythonweb
    spec:
      containers:
      - name: pythonweb
        image: lavanya986/exampython:v1  # Replace with your actual image
        ports:
        - containerPort: 5000
