apiVersion: v1
kind: Service
metadata:
  labels:
    app: pythonweb
  name: pythonweb
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30001  # Expose the service on a specific port, replace with a desired port if needed
  selector:
    app: pythonweb
